---
title: "main"
format: html
---

```{r}
library(readr)
library(dplyr)
NBA_Payroll_1990_2023 <- read_csv("NBA Payroll(1990-2023).csv")
NBA_team_stats_2000_2023 = read_csv("nba_team_stats_00_to_23.csv")
```

```{r}
head(NBA_Payroll_1990_2023)
head(NBA_team_stats_2000_2023)
```
```{r}
(payroll = summarize(NBA_Payroll_1990_2023,team,seasonStartYear,payroll,inflationAdjPayroll))
(team_winrate = summarize(NBA_team_stats_2000_2023,Team,games_played,wins,losses,win_percentage,season))
```

```{r}
team_winrate=mutate(team_winrate,season=substr(season,start=1,stop=4))
names(payroll)[names(payroll) == 'seasonStartYear'] <- 'season'
names(payroll)[names(payroll) == 'team'] <- 'Team'
head(team_winrate)
head(payroll)
team_winrate$Team = gsub("New Orleans/Oklahoma City Hornets","New Orleans Hornets",team_winrate$Team)
team_winrate$Team = gsub("Los Angeles","LA",team_winrate$Team)
team_winrate$Team = gsub("(?!\\sClippers|\\sLakers)(\\s+\\w*$)","",team_winrate$Team,perl=T)
team_winrate$Team = gsub(" Trail","",team_winrate$Team)
#unique(team_winrate$Team)
#gsup("New Orleans/Oklahoma City Hornets")
payrollAndWinrate = merge(payroll,team_winrate,by=c("Team","season"))
```

```{r}
filter(payrollAndWinrate,season==2003)
```


```{r}
playerPPstats2021 = read_csv("player-per-possession-stats-2021-22.txt")
playerTotals2021 = read_csv("player-total-stats-2021-22.txt")
playerSalaries = read_csv("NBA Salaries(1990-2023).csv")
head(playerSalaries)
head(playerPPstats2021)
nrow(playerPPstats2021)
nrow(playerTotals2021)
head(playerTotals2021)
```
```{r}
unique(playerTotals2021$Pos)
(rows= nrow(playerTotals2021))
for (pos in unique(playerTotals2021$Pos)){
  print(pos)
  print(nrow(filter(playerTotals2021,Pos==pos))/rows)
}
```

```{r}
playerTotals2021%>%summarize(mean(`3PA`,na.rm=TRUE),mean(`2PA`,na.rm=TRUE),mean(FTA,na.rm=TRUE),mean(PTS,na.rm=TRUE),mean(`FT%`,na.rm=TRUE))

playerTotals2021%>%summarize(sd(`3PA`,na.rm=TRUE),sd(`2PA`,na.rm=TRUE),sd(FTA,na.rm=TRUE),sd(PTS,na.rm=TRUE),sd(`FT%`,na.rm=TRUE))

playerPPstats2021%>%summarize(mean(`eFG%`,na.rm=TRUE),mean(`FTA`,na.rm=TRUE),mean(PTS,na.rm=TRUE))

playerPPstats2021%>%summarize(sd(`eFG%`,na.rm=TRUE),sd(`FTA`,na.rm=TRUE),sd(PTS,na.rm=TRUE))

playerSalaries$salary = gsub("\\$|,","",playerSalaries$salary)
head(playerSalaries)

playerSalaries$salary <- as.integer(playerSalaries$salary)
playerSalaries %>% filter(seasonStartYear==2021) %>% summarize(sd(salary))
```

